Laboratornaya 2
sviridov6012/Laba2 pull request #1
Opened 2024-10-27 11:25 UTC by sviridov6012

![image](https://github.com/user-attachments/assets/2155c76a-02ef-4861-ab7b-af79be53480f)

2024-10-29 18:05 UTC, rmushkin requested changes
На все ошибки оформления можно бы наплевать, если бы не проблема с округлением во второй части. А раз все равно исправлять, то и прочее исправьте тоже, пожалуйста)

2024-10-29 18:05 UTC, rmushkin commented on Лаба 2/task_1.py
> +print("Количество месяцев, которое можно протянуть без долгов:", months)
Нужна пустая строка в конце файла

2024-10-29 18:05 UTC, rmushkin commented on Лаба 2/task_2.py
> +print(f"Подушка безопасности, чтобы протянуть {months} месяцев без долгов: {money_capital}")
Нужна пустая строка в конце файла

2024-10-29 18:05 UTC, rmushkin commented on Лаба 2/task_2.py
> +money_capital = round(money_capital)
Ловушка с `round`: 3 рублей не хватит, чтобы купить гвоздь за 3 рубля 25 копеек. Надо округлять в большую сторону.

2024-10-29 18:05 UTC, rmushkin commented on Лаба 2/task_2.py
> +    spend *= (1 + increase)
PEP8: скобки излишни

2024-10-29 18:05 UTC, rmushkin commented on Лаба 2/task_2.py
> +for month in range(months):
(не ошибка) питоничнее использовать _ вместо имени переменной. Это полностью валидное имя, т. к. нижнее подчёркивание считается обычной буквой; однако выглядит как "пустое место" и дополнительно самодокументирует код, указывая на неиспользуемость значения.

2024-11-01 15:56 UTC, sviridov6012 commented
![image](https://github.com/user-attachments/assets/6ff71370-02f9-4014-b455-4cb290bfe7fe)
задание №2

2024-11-01 19:59 UTC, rmushkin approved these changes
Принимается ✅

2024-11-01 20:00 UTC, rmushkin commented
А теперь [добавьте](https://docs.github.com/ru/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository), пожалуйста, меня в список коллабораторов, чтобы я мог закрыть пулл-реквест.

2024-11-01 21:37 UTC, sviridov6012 commented
> А теперь [добавьте](https://docs.github.com/ru/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository), пожалуйста, меня в список коллабораторов, чтобы я мог закрыть пулл-реквест.

2024-11-01 22:19 UTC, merged